const FEEDS = [
  // ── WORLD NEWS ────────────────────────────────────────────────────────────
  // EUROPE — english
  { id:'guardian',    cat:'world-news', name:'The Guardian',           flag:'🇬🇧', cc:'GB', lang:'en', region:'Europe',       tags:['independent','longform'], notes:'Centre-left British broadsheet. Strong on environment, global affairs, investigative.',     url:'https://www.theguardian.com/world/rss' },
  { id:'bbc',         cat:'world-news', name:'BBC World',              flag:'🇬🇧', cc:'GB', lang:'en', region:'Europe',       tags:['state-funded','wire'],    notes:'UK public broadcaster. Neutral mandate by charter. Broad geographic coverage.',               url:'https://feeds.bbci.co.uk/news/world/rss.xml' },
  { id:'economist',   cat:'world-news', name:'The Economist',          flag:'🇬🇧', cc:'GB', lang:'en', region:'Europe',       tags:['independent','longform'], notes:'Economically liberal weekly. Exceptional on finance, trade policy, emerging markets.',         url:'https://www.economist.com/the-world-this-week/rss.xml' },
  // FT removed — blocks all CORS proxies. Replaced:
  { id:'reuters',     cat:'world-news', name:'Reuters World',          flag:'🇬🇧', cc:'GB', lang:'en', region:'Europe',       tags:['wire'],                   notes:'Global wire service. Factual, fast, no editorial line. Most-cited source in financial journalism.', url:'https://feeds.reuters.com/reuters/worldNews' },
  { id:'dw',          cat:'world-news', name:'Deutsche Welle',         flag:'🇩🇪', cc:'DE', lang:'en', region:'Europe',       tags:['state-funded'],           notes:'German public broadcaster in English. Good on Central/Eastern European affairs.',               url:'https://rss.dw.com/rdf/rss-en-world' },
  { id:'rfi',         cat:'world-news', name:'RFI English',            flag:'🇫🇷', cc:'FR', lang:'en', region:'Europe',       tags:['state-funded'],           notes:'French public radio in English. Strongest African coverage of any source here.',               url:'https://www.rfi.fr/en/rss' },
  { id:'euronews',    cat:'world-news', name:'Euronews',               flag:'🇪🇺', cc:'EU', lang:'en', region:'Europe',       tags:['independent'],            notes:'Pan-European news. Good on EU institutions, Balkans, Eastern Europe.',                         url:'https://www.euronews.com/rss' },
  // EUROPE — french
  { id:'lemonde',     cat:'world-news', name:'Le Monde',               flag:'🇫🇷', cc:'FR', lang:'fr', region:'Europe',       tags:['independent','longform'], notes:'Newspaper of record in France. Analytical, authoritative, centre-left.',                      url:'https://www.lemonde.fr/rss/une.xml' },
  { id:'letemps',     cat:'world-news', name:'Le Temps',               flag:'🇨🇭', cc:'CH', lang:'fr', region:'Europe',       tags:['independent'],            notes:'Swiss French daily. Liberal, internationally minded. Strong on finance and diplomacy.',         url:'https://www.letemps.ch/articles.rss' },
  { id:'france24fr',  cat:'world-news', name:'France 24',              flag:'🇫🇷', cc:'FR', lang:'fr', region:'Europe',       tags:['state-funded'],           notes:'French international news broadcaster. Strong on Francophone Africa and the Middle East.',      url:'https://www.france24.com/fr/rss' },
  // EUROPE — german
  { id:'spiegel',     cat:'world-news', name:'Der Spiegel',            flag:'🇩🇪', cc:'DE', lang:'de', region:'Europe',       tags:['independent','longform'], notes:'Germany\'s most-read news magazine. Investigative tradition. Centre-left.',                    url:'https://www.spiegel.de/schlagzeilen/index.rss' },
  { id:'zeit',        cat:'world-news', name:'Die Zeit',               flag:'🇩🇪', cc:'DE', lang:'de', region:'Europe',       tags:['independent','longform'], notes:'Weekly broadsheet. Long-form, intellectual. Liberal-progressive.',                             url:'https://newsfeed.zeit.de/index' },
  { id:'nzz',         cat:'world-news', name:'Neue Zürcher Zeitung',   flag:'🇨🇭', cc:'CH', lang:'de', region:'Europe',       tags:['independent'],            notes:'Swiss German daily. Classical liberal, free-market. More conservative than Zeit.',              url:'https://www.nzz.ch/recent.rss' },
  // EUROPE — other
  { id:'publico',     cat:'world-news', name:'Público',                flag:'🇵🇹', cc:'PT', lang:'pt', region:'Europe',       tags:['independent'],            notes:'Portuguese quality daily. Centre-left. Best domestic source for Portugal/Lusophone world.',    url:'https://www.publico.pt/api/rss' },
  { id:'rtp',         cat:'world-news', name:'RTP Notícias',           flag:'🇵🇹', cc:'PT', lang:'pt', region:'Europe',       tags:['state-funded'],           notes:'Portuguese public broadcaster. Broad domestic and lusophone coverage.',                        url:'https://www.rtp.pt/noticias/rss/noticias' },
  { id:'elpais',      cat:'world-news', name:'El País',                flag:'🇪🇸', cc:'ES', lang:'es', region:'Europe',       tags:['independent','longform'], notes:'Spain\'s newspaper of record. Strong on Latin America. Centre-left.',                          url:'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada' },
  { id:'republika',   cat:'world-news', name:'La Repubblica',          flag:'🇮🇹', cc:'IT', lang:'it', region:'Europe',       tags:['independent'],            notes:'Italian daily. Liberal, pro-European. Good on Italian politics and Mediterranean affairs.',    url:'https://www.repubblica.it/rss/homepage/rss2.0.xml' },
  // AMERICAS
  { id:'nyt',         cat:'world-news', name:'New York Times',         flag:'🇺🇸', cc:'US', lang:'en', region:'Americas',     tags:['independent','longform'], notes:'US newspaper of record. Unmatched resources. Centre-left editorial, global reach.',            url:'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml' },
  { id:'ap',          cat:'world-news', name:'Associated Press',       flag:'🇺🇸', cc:'US', lang:'en', region:'Americas',     tags:['wire'],                   notes:'Non-profit wire service. Factual, no editorial line. Feeds most US newspapers.',              url:'https://apnews.com/apf-topnews?format=rss' },
  { id:'npr',         cat:'world-news', name:'NPR World',              flag:'🇺🇸', cc:'US', lang:'en', region:'Americas',     tags:['state-funded'],           notes:'US public radio. Strong on domestic politics and international development.',                  url:'https://feeds.npr.org/1004/rss.xml' },
  { id:'folha',       cat:'world-news', name:'Folha de S.Paulo',       flag:'🇧🇷', cc:'BR', lang:'pt', region:'Americas',     tags:['independent'],            notes:'Brazil\'s most-read quality paper. Essential for Latin American perspective.',                 url:'https://feeds.folha.uol.com.br/mundo/rss091.xml' },
  { id:'lanacion',    cat:'world-news', name:'La Nación',              flag:'🇦🇷', cc:'AR', lang:'es', region:'Americas',     tags:['independent'],            notes:'Argentina\'s oldest daily. Conservative, business-oriented. Good on Southern Cone.',          url:'https://www.lanacion.com.ar/arc/outboundfeeds/rss/' },
  // ASIA-PACIFIC
  { id:'nhk',         cat:'world-news', name:'NHK World',              flag:'🇯🇵', cc:'JP', lang:'en', region:'Asia-Pacific', tags:['state-funded'],           notes:'Japan\'s public broadcaster in English. Measured, diplomatic. Strong on East Asia.',            url:'https://www3.nhk.or.jp/rss/news/cat0.xml' },
  { id:'asahi',       cat:'world-news', name:'朝日新聞',                flag:'🇯🇵', cc:'JP', lang:'ja', region:'Asia-Pacific', tags:['independent'],            notes:'Japan\'s second-largest daily. Liberal, pacifist tradition.',                                 url:'https://www.asahi.com/rss/asahi/newsheadlines.rdf' },
  { id:'scmp',        cat:'world-news', name:'S. China Morning Post',  flag:'🇭🇰', cc:'HK', lang:'en', region:'Asia-Pacific', tags:['independent'],            notes:'Best English-language coverage of China and Southeast Asia.',                                 url:'https://www.scmp.com/rss/91/feed' },
  { id:'straits',     cat:'world-news', name:'The Straits Times',      flag:'🇸🇬', cc:'SG', lang:'en', region:'Asia-Pacific', tags:['independent'],            notes:'Singapore daily. Strong on Southeast Asia, China-ASEAN relations.',                           url:'https://www.straitstimes.com/news/world/rss.xml' },
  { id:'nikkei',      cat:'world-news', name:'Nikkei Asia',            flag:'🇯🇵', cc:'JP', lang:'en', region:'Asia-Pacific', tags:['independent'],            notes:'Best English coverage of Japanese business and Asian financial markets.',                      url:'https://asia.nikkei.com/rss/feed/nar' },
  // MENA
  { id:'aljazeera',   cat:'world-news', name:'Al Jazeera',             flag:'🇶🇦', cc:'QA', lang:'en', region:'MENA',         tags:['state-funded'],           notes:'Qatari-funded. Strong Global South perspective. Essential counterpoint to Western framing.',  url:'https://www.aljazeera.com/xml/rss/all.xml' },
  { id:'haaretz',     cat:'world-news', name:'Haaretz',                flag:'🇮🇱', cc:'IL', lang:'en', region:'MENA',         tags:['independent'],            notes:'Israel\'s oldest daily. Left-liberal. Critical of occupation. Unique domestic perspective.',  url:'https://www.haaretz.com/cmlink/1.4' },
  { id:'arabnews',    cat:'world-news', name:'Arab News',              flag:'🇸🇦', cc:'SA', lang:'en', region:'MENA',         tags:['independent'],            notes:'Saudi-based English-language daily. Essential Gulf and MENA perspective.',                    url:'https://www.arabnews.com/rss.xml' },
  // AFRICA / GLOBAL SOUTH
  { id:'dailymav',    cat:'world-news', name:'Daily Maverick',         flag:'🇿🇦', cc:'ZA', lang:'en', region:'Africa',       tags:['independent','longform'], notes:'South Africa\'s leading investigative outlet. Best African journalism in English.',           url:'https://www.dailymaverick.co.za/feed/' },
  { id:'thewire',     cat:'world-news', name:'The Wire',               flag:'🇮🇳', cc:'IN', lang:'en', region:'Asia-Pacific', tags:['independent'],            notes:'Indian independent journalism. Strong on politics, civil liberties, South Asia.',              url:'https://thewire.in/feed' },
  // ── TECHNOLOGY ────────────────────────────────────────────────────────────
  { id:'mit-tech',    cat:'tech', name:'MIT Tech Review',      flag:'🇺🇸', cc:'US', lang:'en', region:'Analysis',      tags:['independent','longform'], notes:'Rigorous technology journalism from MIT. Best on AI, biotech, and climate tech policy.',     url:'https://www.technologyreview.com/feed/' },
  { id:'ars',         cat:'tech', name:'Ars Technica',          flag:'🇺🇸', cc:'US', lang:'en', region:'Analysis',      tags:['independent'],            notes:'Technical depth rarely found in trade press. Good on computing, science, and policy.',        url:'https://feeds.arstechnica.com/arstechnica/index' },
  { id:'ieee',        cat:'tech', name:'IEEE Spectrum',         flag:'🇺🇸', cc:'US', lang:'en', region:'Institutional', tags:['institutional'],          notes:'Engineering perspective. Underrepresented in most aggregators. Strong on hardware and energy.', url:'https://spectrum.ieee.org/feeds/feed.rss' },
  { id:'register',    cat:'tech', name:'The Register',          flag:'🇬🇧', cc:'GB', lang:'en', region:'Analysis',      tags:['independent'],            notes:'British, sardonic, essential on enterprise, security, and the business of tech.',             url:'https://www.theregister.com/headlines.atom' },
  { id:'rest-world',  cat:'tech', name:'Rest of World',         flag:'🌐', cc:'--', lang:'en', region:'Analysis',      tags:['independent','longform'], notes:'Technology in the Global South. Completely absent from most tech media.',                     url:'https://restofworld.org/feed/latest' },
  { id:'schneier',    cat:'tech', name:'Schneier on Security',  flag:'🇺🇸', cc:'US', lang:'en', region:'Blogs',         tags:['independent'],            notes:'Bruce Schneier\'s blog. Most authoritative security and cryptography voice in public.',       url:'https://www.schneier.com/feed/atom/' },
  { id:'hn',          cat:'tech', name:'Hacker News',           flag:'🌐', cc:'US', lang:'en', region:'Community',     tags:['community'],              notes:'Noisy but collectively intelligent. Surfaces obscure technical papers and startup stories.',   url:'https://hnrss.org/frontpage' },
  { id:'wired',       cat:'tech', name:'Wired',                 flag:'🇺🇸', cc:'US', lang:'en', region:'Analysis',      tags:['independent'],            notes:'Tech culture, policy, science. Best on the social and political dimensions of technology.',    url:'https://www.wired.com/feed/rss' },
  { id:'verge',       cat:'tech', name:'The Verge',             flag:'🇺🇸', cc:'US', lang:'en', region:'Analysis',      tags:['independent'],            notes:'Consumer tech and tech industry. Fast, opinionated, good on Big Tech and policy.',            url:'https://www.theverge.com/rss/index.xml' },
  // Logic Magazine removed — publishes quarterly, always 0 recent items
  // ACM TechNews removed — very low frequency, often empty
  // ── SCIENCE ───────────────────────────────────────────────────────────────
  { id:'quanta',      cat:'science', name:'Quanta Magazine',    flag:'🇺🇸', cc:'US', lang:'en', region:'Journalism',   tags:['independent','longform'], notes:'Best science journalism alive. Rigorous and readable. Covers math, physics, biology, CS.',    url:'https://www.quantamagazine.org/feed/' },
  { id:'nature-news', cat:'science', name:'Nature News',        flag:'🇬🇧', cc:'GB', lang:'en', region:'Journals',     tags:['institutional'],          notes:'News and comment section of Nature. Not paywalled. High-impact research across all sciences.', url:'https://www.nature.com/nature.rss' },
  { id:'new-sci',     cat:'science', name:'New Scientist',      flag:'🇬🇧', cc:'GB', lang:'en', region:'Journalism',   tags:['independent'],            notes:'More accessible than Nature. Broader, UK-based. Good on emerging research.',                   url:'https://www.newscientist.com/feed/home/' },
  { id:'nautilus',    cat:'science', name:'Nautilus',           flag:'🇺🇸', cc:'US', lang:'en', region:'Journalism',   tags:['independent','longform'], notes:'Long-form, explicitly interdisciplinary. Science, philosophy, and culture in conversation.',   url:'https://nautilus.pub/feed/' },
  { id:'phys-org',    cat:'science', name:'Phys.org',           flag:'🌐', cc:'--', lang:'en', region:'Wire',         tags:['wire'],                   notes:'Wire service for physics, astronomy, chemistry. High volume. Good for breadth.',               url:'https://phys.org/rss-feed/' },
  { id:'arxiv-ai',    cat:'science', name:'arXiv CS·AI',        flag:'🌐', cc:'--', lang:'en', region:'Preprints',    tags:['institutional'],          notes:'Raw AI preprints. Very noisy, very current. Nothing is more up-to-date on ML research.',       url:'https://rss.arxiv.org/rss/cs.AI' },
  { id:'science-mag', cat:'science', name:'Science Magazine',   flag:'🇺🇸', cc:'US', lang:'en', region:'Journals',     tags:['institutional'],          notes:'AAAS journal news. Peer of Nature. Strong on policy implications of research.',               url:'https://www.science.org/rss/news_current.xml' },
  { id:'undark',      cat:'science', name:'Undark',             flag:'🇺🇸', cc:'US', lang:'en', region:'Journalism',   tags:['independent','longform'], notes:'Independent science journalism focused on policy, ethics, and society. Non-profit.',           url:'https://undark.org/feed/' },
  { id:'the-scientist', cat:'science', name:'The Scientist',    flag:'🇺🇸', cc:'US', lang:'en', region:'Journalism',   tags:['independent'],            notes:'Life sciences news for researchers. Strong on biotech, medicine, lab technique.',              url:'https://www.the-scientist.com/rss' },
  // ── HUMANITIES & CULTURE ──────────────────────────────────────────────────
  { id:'paris-rev',   cat:'humanities', name:'The Paris Review',      flag:'🇺🇸', cc:'US', lang:'en', region:'Literature', tags:['independent','longform'], notes:'Fiction, poetry, and the best author interviews in print. A benchmark of literary culture.',  url:'https://www.theparisreview.org/feed/' },
  { id:'eurozine',    cat:'humanities', name:'Eurozine',               flag:'🇪🇺', cc:'EU', lang:'en', region:'Essays',    tags:['independent','longform'], notes:'Pan-European cultural and political essays. Genuinely multilingual. Unique in scope.',        url:'https://www.eurozine.com/feed/' },
  { id:'aeon',        cat:'humanities', name:'Aeon',                   flag:'🌐', cc:'--', lang:'en', region:'Essays',    tags:['independent','longform'], notes:'Philosophy, psychology, humanities essays. One of the best general intellectual publications.', url:'https://aeon.co/feed.rss' },
  { id:'public-dom',  cat:'humanities', name:'Public Domain Review',  flag:'🌐', cc:'--', lang:'en', region:'History',   tags:['independent','longform'], notes:'History of ideas through public domain texts and images. Completely unique.',                  url:'https://publicdomainreview.org/rss.xml' },
  { id:'jstor-daily', cat:'humanities', name:'JSTOR Daily',           flag:'🇺🇸', cc:'US', lang:'en', region:'Essays',    tags:['institutional'],          notes:'Accessible essays drawing on JSTOR content. Bridge between academic and general reader.',     url:'https://daily.jstor.org/feed/' },
  { id:'3qd',         cat:'humanities', name:'3 Quarks Daily',        flag:'🌐', cc:'US', lang:'en', region:'Curated',   tags:['community'],              notes:'Human-curated links across science, humanities, arts, politics. Editorially opinionated.',    url:'https://3quarksdaily.com/feed' },
  { id:'lithub',      cat:'humanities', name:'Literary Hub',          flag:'🇺🇸', cc:'US', lang:'en', region:'Literature', tags:['independent'],           notes:'Daily literary news, essays, excerpts. The best aggregator for book culture.',                url:'https://lithub.com/feed/' },
  { id:'aldaily',     cat:'humanities', name:'Arts & Letters Daily',  flag:'🌐', cc:'--', lang:'en', region:'Curated',   tags:['community'],              notes:'Long-running curation of intellectual journalism. Essays, criticism, book reviews.',           url:'https://www.aldaily.com/feed/' },
  { id:'berfrois',    cat:'humanities', name:'Berfrois',               flag:'🌐', cc:'--', lang:'en', region:'Essays',    tags:['independent','longform'], notes:'Literary and intellectual essays, interviews. Underrated. Good on continental philosophy.',    url:'https://www.berfrois.com/feed/' },
  { id:'laphams',     cat:'humanities', name:"Lapham's Quarterly",    flag:'🇺🇸', cc:'US', lang:'en', region:'History',   tags:['independent','longform'], notes:'History and culture through primary sources. Thematic issues. Beautifully edited.',          url:'https://www.laphamsquarterly.org/rss.xml' },
  // ── ECONOMICS ─────────────────────────────────────────────────────────────
  { id:'voxeu',       cat:'economics', name:'VoxEU',                  flag:'🇪🇺', cc:'EU', lang:'en', region:'Research',     tags:['institutional'],          notes:'Economic research translated for policymakers. By CEPR. Free. Rigorous.',                    url:'https://feeds.feedburner.com/voxeu/fYCi' },
  { id:'proj-syn',    cat:'economics', name:'Project Syndicate',      flag:'🌐', cc:'--', lang:'en', region:'Opinion',      tags:['independent'],            notes:'Global op-eds from economists and policymakers. Multilingual. Bretton Woods adjacent.',      url:'https://www.project-syndicate.org/rss' },
  { id:'imf-blog',    cat:'economics', name:'IMF Blog',               flag:'🌐', cc:'--', lang:'en', region:'Institutional', tags:['institutional'],          notes:'Institutional but globally scoped. Good on developing economies and monetary policy.',       url:'https://www.imf.org/en/News/Rss' },
  { id:'nber',        cat:'economics', name:'NBER Digest',            flag:'🇺🇸', cc:'US', lang:'en', region:'Research',     tags:['institutional'],          notes:'National Bureau of Economic Research working papers. Dry but important.',                    url:'https://www.nber.org/rss/new_working_papers.xml' },
  { id:'worldbank',   cat:'economics', name:'World Bank Blog',        flag:'🌐', cc:'--', lang:'en', region:'Institutional', tags:['institutional'],          notes:'Development economics, poverty, climate finance. Broad global coverage.',                    url:'https://blogs.worldbank.org/rss.xml' },
  { id:'ft-alphaville', cat:'economics', name:'FT Alphaville',        flag:'🇬🇧', cc:'GB', lang:'en', region:'Analysis',    tags:['independent'],            notes:'FT\'s free blog on markets and finance. Sharper and funnier than the main paper.',           url:'https://www.ft.com/rss/alphaville' },
  { id:'ourworlddata', cat:'economics', name:'Our World in Data',     flag:'🌐', cc:'--', lang:'en', region:'Research',     tags:['institutional'],          notes:'Data-driven essays on global development, health, energy. Open access. Reliable.',           url:'https://feeds.feedburner.com/OurWorldInData' },
  { id:'caixin',      cat:'economics', name:'Caixin Global',          flag:'🇨🇳', cc:'CN', lang:'en', region:'Asia-Pacific', tags:['independent'],            notes:'China\'s most credible independent business journalism in English.',                         url:'https://www.caixinglobal.com/rss/search/?keywords=&channelList=business' },
  { id:'valor',       cat:'economics', name:'Valor Econômico',        flag:'🇧🇷', cc:'BR', lang:'pt', region:'Americas',     tags:['independent'],            notes:'Brazil\'s leading financial daily. Essential for Latin American markets.',                  url:'https://valor.globo.com/rss/home/valor_economico.xml' },
  { id:'eleconomista',cat:'economics', name:'El Economista',          flag:'🇪🇸', cc:'ES', lang:'es', region:'Europe',       tags:['independent'],            notes:'Spain\'s financial daily. Strong on Ibero-American economics.',                             url:'https://www.eleconomista.es/rss/rss.php?idSector=37' },
  { id:'unctad',      cat:'economics', name:'UNCTAD',                 flag:'🌐', cc:'--', lang:'en', region:'Institutional', tags:['institutional'],          notes:'UN trade and development. Genuinely Global South economic perspective.',                    url:'https://unctad.org/news/rss.xml' },
  { id:'africabiz',   cat:'economics', name:'Africa Business',        flag:'🌍', cc:'--', lang:'en', region:'Africa',        tags:['independent'],            notes:'Sub-Saharan business and investment. Completely absent from most aggregators.',              url:'https://africabusiness.com/feed/' },
  // ── INVESTMENT / VC ────────────────────────────────────────────────────────
  { id:'techcrunch',   cat:'investment', name:'TechCrunch',           flag:'🇺🇸', cc:'US', lang:'en', region:'VC/Startups',  tags:['independent'],            notes:'Leading tech startup, venture capital, and funding news.',                                   url:'https://techcrunch.com/feed/' },
  { id:'crunchbase',   cat:'investment', name:'Crunchbase News',      flag:'🇺🇸', cc:'US', lang:'en', region:'VC/Startups',  tags:['independent'],            notes:'Startup funding, M&A, and venture capital intelligence.',                                    url:'https://news.crunchbase.com/feed/' },
  { id:'dealstreet',   cat:'investment', name:'DealStreetAsia',       flag:'🇸🇬', cc:'SG', lang:'en', region:'Asia',         tags:['independent'],            notes:'Asia-focused PE, VC, and dealmaking. Best on Southeast Asia investment flows.',              url:'https://www.dealstreetasia.com/feed/' },
  { id:'techinasia',   cat:'investment', name:'Tech in Asia',         flag:'🇸🇬', cc:'SG', lang:'en', region:'Asia',         tags:['independent'],            notes:'Tech startup ecosystem across Asia. Good on Indonesia, SEA, India.',                         url:'https://techinasia.com/feed' },
  { id:'krasia',       cat:'investment', name:'KrASIA',               flag:'🇸🇬', cc:'SG', lang:'en', region:'Asia',         tags:['independent'],            notes:'Business and tech news from Asia. Strong on China tech and cross-border investment.',         url:'https://kr-asia.com/feed' },
  { id:'chinadaily',   cat:'investment', name:'China Daily',          flag:'🇨🇳', cc:'CN', lang:'en', region:'China',        tags:['state-funded'],           notes:'Chinese state media in English. Official perspective on Chinese economy and policy.',          url:'https://www.chinadaily.com.cn/rss/china_rss.xml' },
];
